version: '3.8'

services:
  # backend:
  #   container_name: batumbutest_app
  #   build: ./
  #   restart: on-failure
  #   ports:
  #     - "8321:8321"
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ./config:/app/config
  #   depends_on:
  #     # - traefik
  #     - database

  database:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: amarthatest_mysql
    ports:
      - 3999:3306
    environment:
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_USER=denies
      - MYSQL_PASSWORD=deniespassword
      - MYSQL_DATABASE=amarthatest
      - MYSQL_ROOT_PASSWORD=deniespassword
    volumes:
      - database_mysql:/var/lib/mysql

volumes:
  database_mysql: