version: '3.8'

services:
  backend:
    container_name: amarthatest_app
    build: ./
    restart: on-failure
    ports:
      - "8898:8898"
    depends_on:
      - database

  database:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: amarthatest_mysql
    ports:
      - 3999:3306
    environment:
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_USER=denies
      - MYSQL_PASSWORD=deniespassword
      - MYSQL_DATABASE=amarthatest
      - MYSQL_ROOT_PASSWORD=deniespassword
    volumes:
      - database_mysql:/var/lib/mysql

volumes:
  database_mysql: